### ISSUE TITLE
admin界面空白

### ISSUE THREAD

**Issue by jinfagang** [studygolang/studygolang#107]
![image](https://user-images.githubusercontent.com/21303438/56454788-9e0f0f80-6388-11e9-887f-3d69aba3ab9c.png)

**Comment by niqingyang** [comment]
我也是这样，没有任何菜单...

**Comment by polaris1119** [comment]
重启下应该就有了。

**Comment by niqingyang** [comment]
> 重启下应该就有了。

嗯 重启一下就好了，多谢！
