### ISSUE TITLE
首页总是被一些视频教程霸占，考虑优化

### ISSUE THREAD

**Issue by polaris1119** [studygolang/studygolang#111]
每次进入的时候，前几页总是那几个视频教程的帖子，久而久之就有点燥了
可以将这种帖子划分到新的类目，该类新帖按照正常时间推荐，到达一定时间后不再出现在所有文章列表里，而是在固定的教程类栏目里

**Comment by ruyuejun** [comment]
响应速度之快，令人瞠目

**Comment by polaris1119** [comment]
已处理
