### ISSUE TITLE
getpkg.bat 获取依赖库出现重复

### ISSUE THREAD

**Issue by HYQMartin** [studygolang/studygolang#12]
获取crypto出现重复获取，不过有noexit  不影响
if not exist "src/golang.org/x/text" (
	git clone https://github.com/golang/text src/golang.org/x/text
)
go install golang.org/x/text/...

if not exist "src/golang.org/x/crypto" (
	git clone https://github.com/golang/crypto src/golang.org/x/crypto
)
go install golang.org/x/crypto/...

if not exist "src/golang.org/x/crypto" (
	git clone https://github.com/golang/crypto src/golang.org/x/crypto
)
go install golang.org/x/crypto/...

**Comment by polaris1119** [comment]
请按最新文档操作
