### ISSUE TITLE
install一步出错

### ISSUE THREAD

**Issue by leetom** [studygolang/studygolang#13]
按教程一步一步来，到sh install一步出错。
是不是依赖版本不对？

    # server/indexer
    usage: 6l [options] main.6
      -1	use alternate profiling code
      -8	assume 64-bit addresses
      -B info
        	define ELF NT_GNU_BUILD_ID note
      -C	check Go calls to C code
      -D addr
        	data address
      -E sym
        	entry symbol
      -I interp
        	set ELF interp
      -L dir
        	add dir to library path
      -H head
        	header type
      -K	add stack underflow checks
      -O	print pc-line tables
      -Q	debug byte-register code gen
      -R rnd
        	address rounding
      -S	check type signatures
      -T addr
        	text address
      -V	print version and exit
      -W	disassemble input
      -X name value
        	define string data
      -Z	clear stack frame on entry
      -a	disassemble output
      -c	dump call graph
      -d	disable dynamic executable
      -extld ld
        	linker to run in external mode
      -extldflags ldflags
        	flags for external linker
      -f	ignore version mismatch
      -g	disable go package data checks
      -installsuffix suffix
        	pkg directory suffix
      -k sym
        	set field tracking symbol
      -linkmode mode
        	set link mode (internal, external, auto)
      -n	dump symbol table
      -o outfile
        	set output file
      -r dir1:dir2:...
        	set ELF dynamic linker search path
      -race
        	enable race detector
      -s	disable symbol table
      -shared
        	generate shared object (implies -linkmode external)
      -tmpdir dir
        	leave temporary files in this directory
      -u	reject unsafe packages
      -v	print link trace
      -w	disable DWARF generation
    # server/crawlarticle
    usage: 6l [options] main.6
      -1	use alternate profiling code
      -8	assume 64-bit addresses
      -B info
        	define ELF NT_GNU_BUILD_ID note
      -C	check Go calls to C code
      -D addr
        	data address
      -E sym
        	entry symbol
      -I interp
        	set ELF interp
      -L dir
        	add dir to library path
      -H head
        	header type
      -K	add stack underflow checks
      -O	print pc-line tables
      -Q	debug byte-register code gen
      -R rnd
        	address rounding
      -S	check type signatures
      -T addr
        	text address
      -V	print version and exit
      -W	disassemble input
      -X name value
        	define string data
      -Z	clear stack frame on entry
      -a	disassemble output
      -c	dump call graph
      -d	disable dynamic executable
      -extld ld
        	linker to run in external mode
      -extldflags ldflags
        	flags for external linker
      -f	ignore version mismatch
      -g	disable go package data checks
      -installsuffix suffix
        	pkg directory suffix
      -k sym
        	set field tracking symbol
      -linkmode mode
        	set link mode (internal, external, auto)
      -n	dump symbol table
      -o outfile
        	set output file
      -r dir1:dir2:...
        	set ELF dynamic linker search path
      -race
        	enable race detector
      -s	disable symbol table
      -shared
        	generate shared object (implies -linkmode external)
      -tmpdir dir
        	leave temporary files in this directory
      -u	reject unsafe packages
      -v	print link trace
      -w	disable DWARF generation
    # controller
    src/controller/ajax.go:300: undefined: mime.ExtensionsByType

**Comment by polaris1119** [comment]
请按最新文档操作
