### ISSUE TITLE
执行make reload命令进行重新编译，报错

### ISSUE THREAD

**Issue by zhang14725804** [studygolang/studygolang#141]
当前操作系统为ubuntu18，修改代码之后想重新编译，运行make build，make start命令发现并没有重新编译，查看makefile文件，发现有reload，执行make reload，

`
/bin/sh: 1: kill: No such process
Makefile :20: recipe for target 'reload' failed
make:*** [reload] Error 1
`

**Comment by zhang14725804** [comment]
@lunny @feixionglee @polaris1119 @lewgun 那个小哥有空帮忙解答一下

**Comment by polaris1119** [comment]
make start 没启动，看看 log/panic.log 报错没有？

**Comment by zhang14725804** [comment]
@polaris1119 启动了，就是代码里加了一些log日志，想重新编译，怎么才能重新编译呢

**Comment by zhang14725804** [comment]
@polaris1119 怎么才能重新编译代码，再次执行make start不行啊
