### ISSUE TITLE
请问管理后台地址怎么进啊，新手找了好久没找到，谢谢

### ISSUE THREAD

**Issue by samkeke** [studygolang/studygolang#142]

**Comment by zzustu** [comment]
注册一个账户并登录，这时该用户还是普通用户，点击右上角用户名字可以看到如下菜单（我这里以test1为例）：
![01](https://user-images.githubusercontent.com/17822281/76382825-e8c8ba00-6394-11ea-834b-eafeadb4443e.PNG)

打开数据库role_info表记下你用户的id
![03](https://user-images.githubusercontent.com/17822281/76382976-5a086d00-6395-11ea-9e82-377da40382b8.PNG)


打开数据库role表可以看到内置的有如下几种角色，找到你需要的角色id，级别越高权限越大：
![02](https://user-images.githubusercontent.com/17822281/76382900-1b72b280-6395-11ea-851a-27685f9cc79d.PNG)

打开user_role表，将你的用户的roleuid改成高级别的角色并保存，
![04](https://user-images.githubusercontent.com/17822281/76383162-e4e96780-6395-11ea-947f-e6717cfdd67f.PNG)

退出再登录就有后台管理了
![05](https://user-images.githubusercontent.com/17822281/76383226-195d2380-6396-11ea-81f3-957bab49fb1b.PNG)
