### ISSUE TITLE
导入表 studygolang_init.sq的时候出错

### ISSUE THREAD

**Issue by proudlily** [studygolang/studygolang#15]
报错 Table 'studygolang.resource_category' doesn't exist 。。。。这是什么意思呀？

**Comment by proudlily** [comment]
linux 下用别的命令 mysql -u annqlm -p studygolang <studygolang_init.sql
显示：
ERROR 1146 (42S02) at line 2: Table 'studygolang.role' doesn't exist

**Comment by polaris1119** [comment]
请按最新文档操作
