### ISSUE TITLE
安装时一直为空白

### ISSUE THREAD

**Issue by sheepbao** [studygolang/studygolang#17]
我的环境：
`lstbao@lstbao-listome software$ go env`
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lstbao/work/listomego:/home/lstbao/gowork"
GORACE=""
GOROOT="/home/lstbao/software/go"
GOTOOLDIR="/home/lstbao/software/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

`lstbao@lstbao-listome software$ go version`
go version go1.6.2 linux/amd64

当我执行./install.sh，打开localhost:8088时，第一个页面是配置mysql数据库的，到这里都很正常，当我点击*进行安装*时，就一直为空白了，然后我关闭了空白页，重新打开localhost:8088，可以正常访问，但是当我注册用户的时候报错了：
17:05:07.998242 [127.0.0.1 POST /account/register 567206db-cb79-413f-9fbb-426a153a30d5 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36" 200 2.738351ms 12544] user logic UserExists error: Error 1146: Table 'studygolang.user_login' doesn't exist
 user logic UserExists error: Error 1146: Table 'studygolang.user_login' doesn't exist
 内部服务器错误 : Error 1146: Table 'studygolang.user_info' doesn't exist

看了一下源码，点击*进行安装*的路由是/install/do，这时页面显示空白，也就是数据库的表格没创建，导致不能注册，但不知为何没有创建表格，还是说/install/do要很久？。

**Comment by polaris1119** [comment]
数据库创建成功了没？因为 /install/do 需要处理创建数据库和数据表等，所以，会有些耗时。但也不会太长。你可以将 config/env.ini 删除，并把数据库删除，然后启动服务，再访问安装试试？

**Comment by sheepbao** [comment]
有创建数据库，名字为studygolang， 我再试试

**Comment by sheepbao** [comment]
删除了env.ini 和 数据库，依然和以前一样，但是看到了有个error.log文件，文件内容：
18:27:40.506256 [127.0.0.1 GET /install/do 1393cbcb-d08f-4529-8b54-985b99aea5ec "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36" 200 1.843526ms 0] 解析模板出错（ParseFiles）：["/install/do"] template: install.html:16: function "endif" not defined

解析install.html报错了
