### ISSUE TITLE
请问studygolang支持go1.8.3吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [studygolang/studygolang#21]
请问studygolang支持go1.8.3吗？

**Comment by polaris1119** [comment]
支持啊，遇到什么问题了吗？

**Comment by Yakumo-Yukari** [comment]
请问我想在Linux 64位上编译 兼容32位的该怎么修改编译脚本呢

**Comment by polaris1119** [comment]
这就是交叉编译问题，可以参考 http://studygolang.com/articles/5177

**Comment by Yakumo-Yukari** [comment]
好的 谢谢

**Comment by Yakumo-Yukari** [comment]
2017/07/04 17:58:45 fetching golang.org/x/net/websocket
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack 失败
2017/07/04 17:59:52 github.com/labstack/gommon/log: dependency could not be fetched: exit status 128
2017/07/04 17:59:52 fetching golang.org/x/oauth2
2017/07/04 18:01:02 fetching golang.org/x/text/encoding
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack 失败
2017/07/04 18:03:36 github.com/go-xorm/xorm: dependency could not be fetched: exit status 128



麻烦问下，我获取包的时候经常报这个错误怎么解决，需要翻墙获取吗？

**Comment by Yakumo-Yukari** [comment]
fatal: unable to access 'https://github.com/golang/oauth2/': GnuTLS recv error (-54): Error in the pull function.
2017/07/04 18:52:26 golang.org/x/oauth2: dependency could not be fetched: exit status 128
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack 失败
2017/07/04 18:52:45 golang.org/x/net/websocket: dependency could not be fetched: exit status 128
fatal: unable to access 'https://github.com/golang/text/': GnuTLS recv error (-54): Error in the pull function.
2017/07/04 18:53:28 golang.org/x/text/encoding: dependency could not be fetched: exit status 128
fatal: unable to access 'https://github.com/golang/text/': GnuTLS recv error (-54): Error in the pull function.
2017/07/04 18:54:05 golang.org/x/text/internal/tag: dependency could not be fetched: exit status 128

好像一直出现这些错误

**Comment by Yakumo-Yukari** [comment]
root@coco:~/go/src/studygolang# ./start.sh
start successfully


大佬编译完成后也顺利启动了 但是输入ip:8088后无法访问这个页面没有出现图形安装界面，是哪里的问题呢
