### ISSUE TITLE
start.bat启动失败

### ISSUE THREAD

**Issue by xdeng** [studygolang/studygolang#24]
崩溃日志为 
panic: GetFileAttributesEx bin\studygolang: The system cannot find the file specified.

goroutine 1 [running]:
global.init.1()
	C:/Users/xdeng/Desktop/studygolang-2.x/src/global/app.go:86 +0x3a2
global.init()
	C:/Users/xdeng/Desktop/studygolang-2.x/src/global/chan.go:13 +0x18b
main.init()
	C:/Users/xdeng/Desktop/studygolang-2.x/src/server/studygolang/static.go:40 +0x57

代码为
	fileInfo, err := os.Stat(os.Args[0])
	if err != nil {
		panic(err)
	}

启动命令为
start /b bin\studygolang >> log\panic.log 2>&1 &

os.Args[0] == bin\studygolang    找不到的原因是 不存在这个文件。

应该改为 

start /b bin\studygolang.exe >> log\panic.log 2>&1 &    即可。

**Comment by xdeng** [comment]
二进制下载 现在百毒要安装客户端才可以下载了 能不能换个地方啊。

**Comment by Yakumo-Yukari** [comment]
请问你知道，怎么在后台添加发帖时候选择的节点吗 在后台找了半天也没找到在哪里添加

**Comment by polaris1119** [comment]
反馈已收到！

**Comment by polaris1119** [comment]
已解决
