### ISSUE TITLE
db.sql中article没有markdown字段

### ISSUE THREAD

**Issue by nicle-lin** [studygolang/studygolang#28]

**Comment by polaris1119** [comment]
昨天刚加的，最新的代码已经加上。你可以通过 
```sql
alter table articles add column `markdown` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '是否是markwon格式：0-否，1-是' after `top`
``` 
来更新数据库

**Comment by nicle-lin** [comment]
haha, 早已改了

**Comment by nicle-lin** [comment]
/studygolang/src/http/controller/index.go:42 +0x26b
runtime error: index out of range goroutine 8 [running]:
我运行时有个错误，说越界了
就下面这行代码
tab = logic.WebsiteSetting.IndexNavs[0].Tab
