### ISSUE TITLE
执行db.sql报错

### ISSUE THREAD

**Issue by youmisun** [studygolang/studygolang#32]
![_20170811095241](https://user-images.githubusercontent.com/17755936/29198967-346c14fe-7e7b-11e7-8509-7d424b827f9f.png)
![_20170811095304](https://user-images.githubusercontent.com/17755936/29198966-346114aa-7e7b-11e7-8e53-eddf79c0f95c.png)
![_20170811095322](https://user-images.githubusercontent.com/17755936/29198968-347012d4-7e7b-11e7-8646-e470b4bc5e16.png)
![_20170811095345](https://user-images.githubusercontent.com/17755936/29198969-347549de-7e7b-11e7-8583-310d6a23acfa.png)
![_20170811095359](https://user-images.githubusercontent.com/17755936/29198970-34755c62-7e7b-11e7-8771-9c4c98e93c8a.png)
![_20170811095420](https://user-images.githubusercontent.com/17755936/29198971-3476c994-7e7b-11e7-849b-75f954de6dff.png)

**Comment by polaris1119** [comment]
你是啥数据库？MySQL吗？版本是？

**Comment by youmisun** [comment]
是mysql,版本是5.7

**Comment by duanjunxiao** [comment]
切换到mysql5.6即可，mysql5.7重新定义了timestamp的范围。

**Comment by polaris1119** [comment]
@duanjunxiao 原来如此。我也对默认值做了处理！

**Comment by jinfagang** [comment]
@polaris1119 高版本mysql都有这个问题:

```
mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper

```
是否考虑更新一下?
