### ISSUE TITLE
运行后访问http://localhost:8088/ 出现Internal Server Error，控制台打印信息如下

### ISSUE THREAD

**Issue by youmisun** [studygolang/studygolang#33]
![_20170811171148](https://user-images.githubusercontent.com/17755936/29207772-f60584a4-7eb9-11e7-825b-4ea00f6b41bd.png)
![_20170811171225](https://user-images.githubusercontent.com/17755936/29207773-f6171f8e-7eb9-11e7-8d6b-d6d0b903849b.png)

**Comment by nicle-lin** [comment]
作者说最近改动大，还没有搞好，会写一个详细部署文档

**Comment by byteman** [comment]
需要修改config/init.sql 中的'{["tab":"all"]}'  变成 '[{"tab":"all"}]'
