### ISSUE TITLE
怎么支持的https，我看echo改变了不少，用新版本的感觉变动太多了。想问下您是怎么搞的？

### ISSUE THREAD

**Issue by zouhuigang** [studygolang/studygolang#35]
e := echo.New()

	serveStatic(e)

	e.Use(thirdmw.EchoLogger())
	e.Use(mw.Recover())
	e.Use(pwm.Installed(filterPrefixs))
	e.Use(pwm.HTTPError())

	frontG := e.Group("", thirdmw.EchoCache())
	controller.RegisterRoutes(frontG)

	std := standard.New(getAddr())
	std.SetHandler(e)

	//https服务
	//e.Logger.Fatal(e.StartTLS(":443", "/opt/cert/cert.pem", "/opt/cert/key.pem"))
	//e.StartTLS(":443", "/opt/cert/cert.pem", "/opt/cert/key.pem")
	//https服务end

	gracefulRun(std)

**Comment by zouhuigang** [comment]
www.anooc.com这个网站也是根据你的代码修改的，谢谢啦！！[https://github.com/zouhuigang/anooc-golang-docker.git](https://github.com/zouhuigang/anooc-golang-docker.git]

**Comment by zouhuigang** [comment]
www.anooc.com这个网站也是根据你的代码修改的，感谢您的项目！！https://github.com/zouhuigang/anooc-golang-docker.git

**Comment by zouhuigang** [comment]
http://www.anooc.com/

**Comment by polaris1119** [comment]
https 没有使用 echo 的，因为使用了 nginx/caddy 作为反向代理。可以考虑使用 caddy，直接https搞起，很方便

**Comment by polaris1119** [comment]
echo 确实不稳定，经常做大的重构，所以需要版本依赖管理

**Comment by nicle-lin** [comment]
使用beego怎么样？

**Comment by polaris1119** [comment]
没深入了解过 beego

**Comment by zouhuigang** [comment]
好的，谢谢您~
