### ISSUE TITLE
在Mac上路径都多了一个/

### ISSUE THREAD

**Issue by NSObjects** [studygolang/studygolang#36]
./studygolang 
load config file error: open /Users/xx/Documents/Code/GO//config/env.ini: no such file or directory
get mysql config error: section 'mysql' not found
2017/08/30 11:38:51 config parse redis section error: section 'redis' not found
panic: open /Users/xx/Documents/Code/GO//template/email.html: no such file or directory

goroutine 1 [running]:
html/template.Must(0x0, 0x1ad63a0, 0xc42015b320, 0x1)
        /usr/xx/go/src/html/template/template.go:360 +0x54
logic.init()
        /Users/xx/Documents/Code/GO/src/studygolang/src/logic/email.go:126 +0x6e5
main.init()
        /Users/xx/Documents/Code/GO/src/studygolang/src/server/studygolang/static.go:40 +0x5a

**Comment by duanjunxiao** [comment]
你好，我也遇到一样的问题，请问解决了吗？

**Comment by NSObjects** [comment]
@duanjunxiao 到代码里去删除/

**Comment by polaris1119** [comment]
我这的代码没有多 / 呀，你代码是最新的吗？

**Comment by NSObjects** [comment]
昨天拉下来的， 运行脚本就出现这个。go version go1.8.3 darwin/amd64 , macos 10.12.6

**Comment by NSObjects** [comment]
昨天拉下来的。go version go1.8.3 darwin/amd64 , macos 10.12.6, 代码里面import我都去手动改好才能运行 ，"http/middleware" ，需要我手动加studygolang/src/

**Comment by polaris1119** [comment]
受到加这个是什么意思？还有这样的事情？

**Comment by NSObjects** [comment]
我刚拉了份最新的源码，运行完getpkg.sh和install.sh后 在src/studygolang目录下运行main.go会报错。
go run main.go
main.go:10:2: cannot find package "global" in any of:
        /Users/lintao/Documents/Code/GO/src/studygolang/src/vendor/global (vendor tree)
        /usr/local/go/src/global (from $GOROOT)
        /Users/lintao/Documents/Code/GO/src/global (from $GOPATH)
main.go:11:2: cannot find package "http/controller" in any of:
        /Users/lintao/Documents/Code/GO/src/studygolang/src/vendor/http/controller (vendor tree)
        /usr/local/go/src/http/controller (from $GOROOT)
我加上完整路径后才能编译通过，我GOROOT环境变量就是设置在Code/GO文件夹下
"studygolang/src/http/controller/admin"

const mainIniPath = "/config/env.ini"
需要去掉前面的/不然有路径问题。

**Comment by NSObjects** [comment]
要手动加是goimports,gofmt都不起作用。。。

**Comment by polaris1119** [comment]
install.sh 后，为啥执行 go run main.go ，应该执行 bin/studygolang

**Comment by hiyanxu** [comment]
根据和大神@polaris1119的沟通，studygolang是一个独立的项目，不可以放到$GOPATH下的src目录下，修改后就可以运行了
