### ISSUE TITLE
bin/studygolang: 没有那个文件或目录

### ISSUE THREAD

**Issue by duanjunxiao** [studygolang/studygolang#37]
你好 ./getpkg.sh ./install.sh ./start.sh 都执行成功，但是没有在当前目录下生成bin/studygolang 服务启动不了
tail -f log/panic.log
./start.sh:行21: bin/studygolang: 没有那个文件或目录

**Comment by polaris1119** [comment]
是不是你设置了 GOBIN 环境变量？你 echo $GOBIN 看看

**Comment by duanjunxiao** [comment]
我没有设置GOBIN
Mac-mini:~ bash$ echo $GOBIN

Mac-mini:~ bash$

**Comment by duanjunxiao** [comment]
嗯嗯 是的 找到问题了 谢谢啊🙏

**Comment by duanjunxiao** [comment]
你好 还是有panic

http/controller.IndexController.NewIndex(0x1ae98c0, 0xc4201e6480, 0x17988db, 0x5)
	/Users/duanjunxiao/golang/src/github.com/studygolang/studygolang/src/http/controller/index.go:42 +0x2d4
http/controller.(IndexController).NewIndex-fm(0x1ae98c0, 0xc4201e6480, 0x17988db, 0x5)
	/Users/duanjunxiao/golang/src/github.com/studygolang/studygolang/src/http/controller/index.go:30 +0x3b

**Comment by polaris1119** [comment]
你到管理后台，设置中配置至少一个首页 TAB 导航（理论上默认会有一个 全部 tab 的）
上次做了一次大改版，我得找时间好好调试下，更方便大家本地搭建环境。

**Comment by duanjunxiao** [comment]
嗯嗯 太感谢了 解决了
