### ISSUE TITLE
我编译成功了，运行页眉提示错误，但是访问不了

### ISSUE THREAD

**Issue by thxallvu** [studygolang/studygolang#42]
`[nbm@192 studygolang]$ ./install.sh 
finished
[nbm@192 studygolang]$ ./start.sh 
start successfully`
访问127.0.0.1:8088不能访问，不知道哪里出问题了，求助！
程序：master
编译安装过程没有异常
mysql和redis也安装好了。

**Comment by thxallvu** [comment]
db.sql需要自己手动导入数据库吗？

**Comment by polaris1119** [comment]
你看下 log 下面的 panic.log 和 error.log

db.sql 不需要手动，会有安装过程，都自动的

**Comment by thxallvu** [comment]
我看了log目录下只有panic.log，说是找不到mysql还有redis，应该是没有env.ini，但是根据说明env.ini是访问127.0.0.1:8088后由env.sample.ini生成的，所以不知道哪里出问题了

**Comment by polaris1119** [comment]
页面访问是空白？看请求是500错误吗？

**Comment by thxallvu** [comment]
访问是空白，我记得火狐浏览器提示不能访问

**Comment by polaris1119** [comment]
方便时加我 QQ 沟通吧 274768166

**Comment by thxallvu** [comment]
果然是目录所致，studygolang目录放到GOPATH下就好了
