### ISSUE TITLE
sublime命令行乱码

### ISSUE THREAD

**Issue by whdwsl** [studygolang/studygolang#7]
各位， win7或ubunt下面安装完sublime+gosublime后，执行一个错误的命令时，显示乱码，如：通过ctrl+b进入命令行，执行：evn   回车，显示乱码。但helloworld执行时 能显示中文。请问命令行乱码怎么解决？感谢！！！

**Comment by polaris1119** [comment]
理论上，ubuntu中应该不会乱码吧？这里有一个链接：[Windows CMD 中文乱码】(http://studygolang.com/wiki/cmd_zh_code)，看对你是否有用处
