### ISSUE TITLE
安装到服务器后出现这个错误

### ISSUE THREAD

**Issue by 756445638** [studygolang/studygolang#70]
该网页无法正常运作
www.xxxx.site 将您重定向的次数过多。
尝试清除 Cookie.
ERR_TOO_MANY_REDIRECTS

**Comment by 756445638** [comment]
后台管理->角色管理也不能使用

**Comment by killernova** [comment]
我也有问题：
1. 安装后后台功能列表是空的，只能去源码中找路由手动写入具体的url
2. 除了刚开始注册的admin，后续注册新用户都直接500错误，看日志说是 `runtime error: index out of range goroutine 11201`
3. 当没有文章时，点击文章列表会报错。
4. 即使在后台设置了新的节点，并在数据库中手动设置为推荐节点，这些节点也只能在后台节点列表中看到，当新建主题时，选择节点列表为空，无法创建节点。
5. 即使我在数据库中手动创建主题，在首页也无法显示主题列表。

我是按照推荐的步骤安装的，安装过程貌似没有什么错误。唯一不同的是：原本我是装在GOPATH的src下的，后来按照指引移到了其它目录。

**Comment by polaris1119** [comment]
@killernova 确定是最新代码吗？会出现编译错误吧

**Comment by thxallvu** [comment]
我也出现了这个问题。前台文章和项目提示重定向次数过多被浏览器阻止了。后台用户角色管理报错。请问是怎么解决的呢？

**Comment by 756445638** [comment]
我后面没有使用这个项目
