### ISSUE TITLE
下载不下来

### ISSUE THREAD

**Issue by allenisready** [studygolang/studygolang#9]
package github.com/qiniu/api
	imports github.com/qiniu/api
	imports github.com/qiniu/api: no buildable Go source files in /Users/kelunliu/studygolang/websites/code/thirdparty/src/github.com/qiniu/api麻烦楼主看下

**Comment by brasbug** [comment]
github.com/andybalholm/cascadia (download)
Fetching https://golang.org/x/net/html?go-get=1

下载失败
https fetch failed.
import "golang.org/x/net/html": https fetch: Get https://golang.org/x/net/html?go-get=1: dial tcp 127.0.0.1:443: getsockopt: connection refused
package golang.org/x/net/html: unrecognized import path "golang.org/x/net/html"

**Comment by polaris1119** [comment]
请按最新文档操作
